### ISSUE TITLE
Function  ATC_SetEvents does not add count events to struct ATC_HandleTypeDef *hAtc

### ISSUE THREAD

**Issue by pvvitali** [nimaltd/atc#12]
hAtc->Events  => is always =0;

`bool ATC_SetEvents(ATC_HandleTypeDef* hAtc, const ATC_EventTypeDef* psEvents)
{
  bool answer = false;
  uint32_t ev = 0;
  do
  {
    if (hAtc == NULL)
    {
      break;
    }
    if (psEvents == NULL)
    {
      break;
    }
    while ((psEvents[ev].Event != NULL) && (psEvents[ev].EventCallback != NULL))
    {
      ev++;
    }
    hAtc->psEvents = (ATC_EventTypeDef*)psEvents;
    hAtc->Events = ev; // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! please add this string!!!!!
    answer = true;

  } while (0);

  return answer;
}`

**Comment by nimaltd** [comment]
thanks for reports. I fixed.
